config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /en|es/ do
    resources :notes, path: ''
    root to: "notes#index"
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  before_validation :trimInput
  validates :title, :body, presence: true, uniqueness: true

  def self.search_by_title(keywords)
    keywords.split.reduce(self) do |acc, word|
      acc.where "title LIKE ? ESCAPE '\\' OR body LIKE ? ESCAPE '\\'", "%#{escape_sql_pattern word}%", "%#{escape_sql_pattern word}%"
    end
  end

  private

  def self.escape_sql_pattern(pattern)
    pattern.gsub(/[%_\\]/, '\\\\\\&')
  end

  def trimInput
    self.title = title.strip unless title.nil?
    self.body = body.strip unless body.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale 
  end
  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  def index()
    
    filters = params[:filters]&.to_unsafe_h&.symbolize_keys
    puts "FILTERS " + filters.inspect
    res = filters ?  filters[:sort_id] : "created_at DESC"
    @notes = Note.order(res)
    if(filters && (filters[:sort_id] == "created_at DESC" || filters[:sort_id] == "created_at ASC" ))
      @notes = @notes.group_by {|note| note.created_at.month}
      @notes = @notes.flatten(2)
    elsif not filters
      @notes = @notes.group_by {|note| note.created_at.month}
      @notes = @notes.flatten(2)
    end
    
    if filters && filters[:query].present? && filters[:sort_id].present? 
      type = filters[:sort_id].split(" ")
      if type[0] == 'created_at' && type[1].match(/\A(asc|desc)\z/i)
        @notes = Note.order(created_at: type[1])
        @notes = @notes.search_by_title(filters[:query] || " ")
        @notes = @notes.group_by {|note| note.created_at.month}
        @notes = @notes.flatten(2)
      elsif type[0] == 'title' && type[1].match(/\A(asc|desc)\z/i)
        @notes = Note.order(title: type[1])
        @notes = @notes.search_by_title(filters[:query] || " ")
      end
    end

    @notes
  end

 
  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_as_localtime(datetime, format = '')
    format = "%d/%b/%Y, %H:%M:%S" unless format.present?
    datetime.localtime.strftime format
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My note collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name = "turbolinks-visit-control" content="reload">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', media: 'all'%>

  </head>

  <body>
   <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <%= link_to notes_path, class: 'brand-logo center' do %>
            <%=t('app_title')%>
          <% end %>
          <a href="#" data-target ="mobile-demo" class="rigth sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li >
              <a id="themeBtn" class="waves-effect waves-light btn ">
                <%=t('darkmode')%>
              </a>  
            <li> <%=link_to "Español", url_for(locale:'es'), class: "btn btn-primary" %></li>
            <li> <%=link_to "English", url_for(locale:'en'), class: "btn btn-primary" %></li>
            </li>
          </ul>
        </div>

      </nav>
    </div> 
      <ul id="mobile-demo" class="sidenav">
        <li >
          <a id="themeBtn" class="waves-effect waves-light btn ">
            <%=t('darkmode')%>
          </a>  
        <li> <%=link_to "Español", url_for(locale:'es'), class: "btn btn-primary" %></li>
        <li> <%=link_to "English", url_for(locale:'en'), class: "btn btn-primary" %></li>
        </li>
      </ul>

    <div class="container ">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(note.errors.count, "error") + t('error_message_title')%> </h5>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" style="margin-top: 7mm">
    <div class="input-field col s12">
      <%= form.text_field :title, autofocus: true, class: ' '%>
      <%= form.label :title, t('title') %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :body, class: 'materialize-textarea  ' %>
      <%= form.label :body, t('body') %>
    </div>
  </div>

  <div class="row ">
    <div class="col s12 right-align">
      <button class="btn-flat waves-effect waves-light" type="submit" >
        <%= material_icon.send %>
      </button>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <%= form_for :filters, html: { class: 'input-field col s12' }, method: 'get' do |form| %>
  <div class="row">
    <div class="col s12 m9 l9">
      <%= material_icon.search.css_class('prefix') %>
      <%= form.text_field :query, autofocus: true, placeholder: t('search_placeholder'), value: params.dig(:filters, :query) %>
    </div>
    <div class="col s12 m3 l3">
      <%= form.select :sort_id, [[t('sorting')[0], 'created_at ASC'], [t('sorting')[1], 'created_at DESC'], [t('sorting')[2], 'title ASC'], [t('sorting')[3], 'title DESC']] %>
      <%= form.submit 'Buscar', :name => ''%>
    </div>  
  </div>
  <% end %>
  
    <% @notes.each do |note|%>
      <% if note.is_a?(Numeric)%>
        <p class="month-section"> 
          <%= t('date.month_names')[note]%>
        </p>
        <div class="divider"></div>
      <% else %>
        <%= link_to note_path(note) do %>
          <div class="col s12 m6 l4">
            <div class="card">
              <div class="card-content">
                <span class="card-title">
                  <%= note.title %>
                  <span class="right" style="font-size: 50%">
                    <%= format_as_localtime note.created_at %>
                  </span>
                </span>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
</div>

<div class="fixed-action-btn tooltipped" data-tooltip ="Create new note" data-position="bottom">
  <%= link_to new_note_path, title: t('new_tooltip'), class: 'btn-floating btn-large pulse' do %>
    <%= material_icon.add %>
  <% end %>
</div>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content  ">
        <span class="card-title">
          <%= @note.title %>
          <span class="right" style="font-size: 50%">
            <%= format_as_localtime @note.created_at %>
          </span>
        </span>
        <p style="white-space: pre-line"><%= @note.body %></p>
      </div>
      <div class="card-action  ">
        <%= link_to @note, title: t('delete_tooltip'), method: :delete, data: { confirm: t('confirmation_message')}, class: '' do %>
          <%= material_icon.delete %>
        <% end %>

        <%= link_to edit_note_path(@note), title: t('edit_tooltip'), class: ' right' do %>
          <%= material_icon.mode_edit %>
        <% end %>
      </div>
    </div>
  </div>
</div>